stages:
  - deploy

include:
  - local: ci/deploy-indore-prod.yml
  - local: ci/deploy-noida-prod.yml
  - local: ci/deploy-indore.yml
  - local: ci/deploy-noida.yml
  - local: ci/deploy-dev-indore.yml
  - local: ci/deploy-dev-noida.yml
