import React, { useState, useEffect } from 'react'
import {
  CCard,
  CCardBody,
  CCardHeader,
  CCol,
  CRow,
  CButton,
  CForm,
  CFormInput,
  CFormLabel,
  CFormTextarea,
  CFormSelect,
  CAlert,
  CSpinner,
} from '@coreui/react'
import { useNavigate, useParams } from 'react-router-dom'
import groupService from '../../services/groupService'
import { Loader } from '../../components'
import { withMinimumDelay } from '../../utils/withMinimumDelay'
import { toastSuccess, toastError } from '../../utils/toast'

const GroupForm = () => {
  const navigate = useNavigate()
  const { id } = useParams()
  const isEdit = Boolean(id)

  const [formData, setFormData] = useState({
    name: '',
    code: '',
    description: '',
    status: 'active',
    sortOrder: 0,
  })

  const [loading, setLoading] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!isEdit) {
      setFormData({
        name: '',
        code: '',
        description: '',
        status: 'active',
        sortOrder: 0,
      })
      return
    }

    const fetchGroup = async () => {
      setLoading(true)
      try {
        const res = await withMinimumDelay(() => groupService.getById(id))
        const group = res?.data || res

        setFormData({
          name: group.name || '',
          code: group.code || '',
          description: group.description || '',
          status: group.status || 'active',
          sortOrder: group.sortOrder ?? 0,
        })
      } catch (err) {
        setError('Failed to load group details')
      } finally {
        setLoading(false)
      }
    }

    fetchGroup()
  }, [id, isEdit])

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData((prev) => ({
      ...prev,
      [name]: name === 'sortOrder' ? (value === '' ? 0 : parseInt(value, 10)) : value,
    }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setSubmitting(true)
    setError('')

    try {
      const { code: _omit, ...rest } = formData
      const payload = {
        ...rest,
        sortOrder: parseInt(formData.sortOrder, 10) || 0,
      }
      if (isEdit) {
        await groupService.update(id, payload)
        toastSuccess('Group updated successfully')
      } else {
        await groupService.create(payload)
        toastSuccess('Group created successfully')
      }
      navigate('/groups')
    } catch (err) {
      toastError(err?.message || 'Failed to save group')
    } finally {
      setSubmitting(false)
    }
  }

  if (loading) {
    return (
      <div className="text-center py-5">
        <Loader message="Loading group..." />
      </div>
    )
  }

  const title = isEdit ? 'Edit Group' : 'Add Group'

  return (
    <CRow>
      <CCol xs={12}>
        <CCard>
          <CCardHeader>
            <strong>{title}</strong>
          </CCardHeader>

          <CCardBody>
            {error && (
              <CAlert color="danger" dismissible onClose={() => setError('')}>
                {error}
              </CAlert>
            )}

            <CForm onSubmit={handleSubmit}>
              <CRow className="mb-3">
                <CCol md={6} className="mb-3 mb-md-0">
                  <CFormLabel>Name *</CFormLabel>
                  <CFormInput
                    name="name"
                    value={formData.name}
                    onChange={handleChange}
                    required
                  />
                </CCol>
                <CCol md={6}>
                  <CFormLabel>Code</CFormLabel>
                  <CFormInput
                    name="code"
                    value={formData.code || ''}
                    placeholder={isEdit ? '' : 'Auto-generated (e.g. GRP01)'}
                    readOnly
                    disabled
                    className="bg-light"
                  />
                  {!isEdit && (
                    <small className="text-muted">Generated by the server on save.</small>
                  )}
                </CCol>
              </CRow>

              <CRow className="mb-3">
                <CCol md={6} className="mb-3 mb-md-0">
                  <CFormLabel>Status</CFormLabel>
                  <CFormSelect
                    name="status"
                    value={formData.status}
                    onChange={handleChange}
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                  </CFormSelect>
                </CCol>
                <CCol md={6}>
                  <CFormLabel>Sort Order</CFormLabel>
                  <CFormInput
                    type="number"
                    name="sortOrder"
                    value={formData.sortOrder}
                    onChange={handleChange}
                    min={0}
                  />
                </CCol>
              </CRow>

              <div className="mb-4">
                <CFormLabel>Description</CFormLabel>
                <CFormTextarea
                  name="description"
                  rows={4}
                  value={formData.description}
                  onChange={handleChange}
                  placeholder="Enter group description..."
                />
              </div>

              <div className="d-flex justify-content-end gap-2 pt-2">
                <CButton color="secondary" variant="outline" onClick={() => navigate('/groups')}>
                  Cancel
                </CButton>
                <CButton color="primary" type="submit" disabled={submitting}>
                  {submitting ? (
                    <>
                      <CSpinner size="sm" className="me-2" />
                      Saving...
                    </>
                  ) : isEdit ? (
                    'Update Group'
                  ) : (
                    'Create Group'
                  )}
                </CButton>
              </div>
            </CForm>
          </CCardBody>
        </CCard>
      </CCol>
    </CRow>
  )
}

export default GroupForm
