import React from "react";
import CIcon from "@coreui/icons-react";
import {
  cilSpeedometer,
  cilBuilding,
  cilLocationPin,
  cilCart,
  cilCommentSquare,
  cilDescription,
  cilPeople,
  cilFactory,
  cilIndustry,
  cilBell,
  cilUser,
  cilLayers,
  cilTags,
  cilList,
  cilMap,
  cilStar,
  cilClipboard,
  cilFolder,
  cilTask,
  cilChartLine,
  cilCalendar,
  cilBasket,
  cilMoney,
  cilTruck,
  cilClock,
  cilCheckCircle,
} from "@coreui/icons";
import { CNavItem, CNavGroup } from "@coreui/react";

// Purchase Manager / Purchase Executive – reference nav (permission-filter if wired to sidebar)
export const PURCHASE_ROLE_NAV = [
  {
    component: CNavItem,
    name: "Pro Dashboard",
    to: "/pro-dashboard",
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    module: "pro_bucket",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Procurement Bucket",
    to: "/purchase-tasks",
    icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
    module: "purchase_tasks",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Follow up Bucket",
    to: "/follow-up",
    icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
    module: "follow_up",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "DMG Bucket",
    to: "/dmg",
    icon: <CIcon icon={cilFolder} customClassName="nav-icon" />,
    module: "dmg",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Pro Bucket",
    to: "/pro-bucket",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: "pro_bucket",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "PO Bucket",
    to: "/po-bucket",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: "po_bucket",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "PO payment",
    to: "/po-payment",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    module: "po_payment",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Inventory bucket",
    to: "/inventory-bucket",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: "inventory_bucket",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Dispatchment",
    to: "/dispatchment",
    icon: <CIcon icon={cilTruck} customClassName="nav-icon" />,
    module: "dispatchment",
    roles: ["purchase_manager", "purchase_exicutive", "procurement"],
  },
];

// Define which roles can access each menu item
// 'module' maps to the RBAC permission module key for granular access control
// Full-access roles (super_admin, admin, hod) bypass permission checks
const _nav = [
  {
    component: CNavItem,
    name: "Dashboard",
    to: "/dashboard",
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    module: null, // Shown unless employee has granular permissions (see AppSidebar)
  },
  {
    component: CNavItem,
    name: "Pro Dashboard",
    to: "/pro-dashboard",
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    module: "pro_bucket",
  },
  {
    component: CNavItem,
    name: "Employee locations",
    to: "/employee-locations",
    icon: <CIcon icon={cilMap} customClassName="nav-icon" />,
    module: null,
    roles: ["head_of_department", "hod"],
  },
  {
    component: CNavItem,
    name: "Companies",
    to: "/companies",
    icon: <CIcon icon={cilBuilding} customClassName="nav-icon" />,
    module: "companies",
  },
  {
    component: CNavItem,
    name: "Branches",
    to: "/branches",
    icon: <CIcon icon={cilLocationPin} customClassName="nav-icon" />,
    module: "branches",
  },
  {
    component: CNavItem,
    name: "Zones",
    to: "/zones",
    icon: <CIcon icon={cilMap} customClassName="nav-icon" />,
    module: "zones",
  },
  {
    component: CNavItem,
    name: "SubZone",
    to: "/sub-zones",
    icon: <CIcon icon={cilLayers} customClassName="nav-icon" />,
    module: "sub_zones",
  },
  {
    component: CNavItem,
    name: "Clients",
    to: "/industries",
    icon: <CIcon icon={cilIndustry} customClassName="nav-icon" />,
    module: "industries",
  },
  {
    component: CNavGroup,
    name: "Product Management",
    to: "/products",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: "products",
    items: [
      {
        component: CNavItem,
        name: "Groups",
        to: "/groups",
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
        module: "groups",
      },
      {
        component: CNavItem,
        name: "Categories",
        to: "/categories",
        icon: <CIcon icon={cilLayers} customClassName="nav-icon" />,
        module: "categories",
      },
      {
        component: CNavItem,
        name: "Brands",
        to: "/brands",
        icon: <CIcon icon={cilTags} customClassName="nav-icon" />,
        module: "brands",
      },
      {
        component: CNavItem,
        name: "Products",
        to: "/products",
        icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
        module: "products",
      },
    ],
  },
  {
    component: CNavItem,
    name: "Product Lead",
    to: "/product-lead",
    icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
    module: "products",
  },
  {
    component: CNavItem,
    name: "Queries",
    to: "/queries",
    icon: <CIcon icon={cilCommentSquare} customClassName="nav-icon" />,
    module: "queries",
  },
  {
    component: CNavItem,
    name: "Quotations",
    to: "/quotations",
    icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
    module: "quotations",
  },
  {
    component: CNavItem,
    name: "Suppliers",
    to: "/suppliers",
    icon: <CIcon icon={cilFactory} customClassName="nav-icon" />,
    module: "suppliers",
  },
  {
    component: CNavItem,
    name: "Rate Card",
    to: "/rate-cards",
    icon: <CIcon icon={cilList} customClassName="nav-icon" />,
    module: "rate_cards",
  },
  {
    component: CNavItem,
    name: "Task Dashboard",
    to: "/task-dashboard",
    icon: <CIcon icon={cilTask} customClassName="nav-icon" />,
    module: "task_management",
  },
  {
    component: CNavItem,
    name: "Task Bucket",
    to: "/task-bucket",
    icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
    module: "task_bucket",
  },
  {
    component: CNavItem,
    name: "Pro Bucket",
    to: "/pro-bucket",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: "pro_bucket",
  },
  {
    component: CNavItem,
    name: "Purchase Bucket",
    to: "/purchase-bucket",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: "purchase_bucket",
  },
  {
    component: CNavItem,
    name: "PO Bucket",
    to: "/po-bucket",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: "po_bucket",
  },
  {
    component: CNavItem,
    name: "Inventory bucket",
    to: "/inventory-bucket",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: "inventory_bucket",
  },
  {
    component: CNavItem,
    name: "Dispatchment",
    to: "/dispatchment",
    icon: <CIcon icon={cilTruck} customClassName="nav-icon" />,
    module: "dispatchment",
  },
  {
    component: CNavItem,
    name: "Delivery approval",
    to: "/delivery-approval",
    icon: <CIcon icon={cilCheckCircle} customClassName="nav-icon" />,
    roles: ["super_admin", "admin", "head_of_department", "hod"],
  },
  {
    component: CNavItem,
    name: "Branch Analytics",
    to: "/branch-analytics",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: "branch_analytics",
  },
  {
    component: CNavItem,
    name: "Target Analytics",
    to: "/target-analytics",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: "target_analytics",
  },
  {
    component: CNavItem,
    name: "Purchase Order",
    to: "/purchase-order-sidebar",
    icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
    module: "po_payment",
  },
  {
    component: CNavItem,
    name: "PO payment",
    to: "/po-payment",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    module: "po_payment",
  },
  {
    component: CNavItem,
    name: "Pending payment",
    to: "/pending-payment",
    icon: <CIcon icon={cilClock} customClassName="nav-icon" />,
    module: "po_payment",
    /** Only roles whose normalized name starts with `sales` (e.g. sales_manager). */
    rolePrefix: "sales",
  },
  {
    component: CNavItem,
    name: "Billing request",
    to: "/billing-requests",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    module: "billing_request",
  },
  {
    component: CNavItem,
    name: "Employees",
    to: "/employees",
    icon: <CIcon icon={cilUser} customClassName="nav-icon" />,
    module: "employees",
  },
  {
    component: CNavItem,
    name: "Visit Management",
    to: "/visit-management-sidebar",
    icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
    module: "visit_management",
  },
  {
    component: CNavItem,
    name: "My Visits",
    to: "/my-visits",
    icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
    module: "my_visits",
  },
];

export default _nav;
