import React from "react";
import CIcon from "@coreui/icons-react";
import {
  cilSpeedometer,
  cilBuilding,
  cilLocationPin,
  cilCart,
  cilCommentSquare,
  cilDescription,
  cilPeople,
  cilFactory,
  cilIndustry,
  cilBell,
  cilUser,
  cilLayers,
  cilTags,
  cilList,
  cilMap,
  cilStar,
  cilClipboard,
  cilFolder,
  cilTask,
  cilChartLine,
  cilCalendar,
  cilBasket,
  cilMoney,
  cilTruck,
  cilClock,
  cilCheckCircle,
  cilOptions,
} from "@coreui/icons";
import { CNavItem, CNavGroup } from "@coreui/react";

// Purchase Executive – reference nav (permission-filter if wired to sidebar)
export const PURCHASE_ROLE_NAV = [
  {
    component: CNavItem,
    name: "Pro Dashboard",
    to: "/pro-dashboard",
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    module: "pro_bucket",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Procurement Bucket",
    to: "/purchase-tasks",
    icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
    module: "purchase_tasks",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Follow up Bucket",
    to: "/follow-up",
    icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
    module: "follow_up",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "DMG Bucket",
    to: "/dmg",
    icon: <CIcon icon={cilFolder} customClassName="nav-icon" />,
    module: "dmg",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Pro Bucket",
    to: "/pro-bucket",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: "pro_bucket",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Local Pro",
    to: "/local-pro",
    icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
    roles: ["procurement"],
  },
  {
    component: CNavItem,
    name: "My Pro Bucket",
    to: "/local-pro",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    roles: ["localprocurement"],
  },
  {
    component: CNavItem,
    name: "Local Purchase",
    to: "/local-purchase",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: "purchase_bucket",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "My Purchase",
    to: "/my-purchase",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    roles: ["localpurchase"],
  },
  {
    component: CNavItem,
    name: "Sales Order Bucket",
    to: "/po-bucket",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: "po_bucket",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Sales Order payment",
    to: "/po-payment",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    module: "po_payment",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Inventory bucket",
    to: "/inventory-bucket",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: "inventory_bucket",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Dispatchment",
    to: "/dispatchment",
    icon: <CIcon icon={cilTruck} customClassName="nav-icon" />,
    module: "dispatchment",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Suppliers",
    to: "/suppliers",
    icon: <CIcon icon={cilFactory} customClassName="nav-icon" />,
    module: "suppliers",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Purchase Bucket",
    to: "/purchase-bucket",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: "purchase_bucket",
    roles: ["purchase_exicutive", "procurement"],
  },
  {
    component: CNavItem,
    name: "Batch Billing Requests",
    to: "/batch-billing-requests",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    rolePrefix: "purchase",
    roles: ["purchase_exicutive", "procurement"],
  },
];

// Define which roles can access each menu item
// 'module' maps to the RBAC permission module key for granular access control
// Full-access roles (super_admin, admin, hod) bypass permission checks
const _nav = [
  {
    component: CNavGroup,
    name: "Dashboard",
    to: "/dashboard",
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "HOD Dashboard",
        to: "/hod-dashboard",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: null,
        roles: ["head_of_department", "hod"],
      },
      {
        component: CNavItem,
        name: "Sales Dashboard",
        to: "/sales-dashboard",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: null,
      },
      {
        component: CNavItem,
        name: "Purchase Dashboard",
        to: "/purchase-dashboard",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        rolePrefix: "purchase",
      },
      {
        component: CNavItem,
        name: "Finance Dashboard",
        to: "/finance",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "finance",
      },
      {
        component: CNavItem,
        name: "Pending Actions",
        to: "/pending-actions",
        icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
        roles: ["head_of_department", "hod"],
      },
    ],
  },
  {
    component: CNavItem,
    name: "Pro Dashboard",
    to: "/pro-dashboard",
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    module: "pro_bucket",
  },
  {
    component: CNavItem,
    name: "Employee locations",
    to: "/employee-locations",
    icon: <CIcon icon={cilMap} customClassName="nav-icon" />,
    module: null,
    roles: ["head_of_department", "hod"],
  },
  {
    component: CNavGroup,
    name: "Product Master",
    to: "/products",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: "products",
    items: [
      {
        component: CNavItem,
        name: "Group",
        to: "/groups",
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
        module: "groups",
      },
      {
        component: CNavItem,
        name: "Categories",
        to: "/categories",
        icon: <CIcon icon={cilLayers} customClassName="nav-icon" />,
        module: "categories",
      },
      {
        component: CNavItem,
        name: "Sub Categories",
        to: "/sub-categories",
        icon: <CIcon icon={cilLayers} customClassName="nav-icon" />,
        module: "categories",
      },
      {
        component: CNavItem,
        name: "Brands",
        to: "/brands",
        icon: <CIcon icon={cilTags} customClassName="nav-icon" />,
        module: "brands",
      },
      {
        component: CNavItem,
        name: "Products",
        to: "/products",
        icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
        module: "products",
      },
      {
        component: CNavItem,
        name: "Product Sale List",
        to: "/product-sale-list",
        icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
        module: "products",
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Query Master",
    to: "/queries",
    icon: <CIcon icon={cilCommentSquare} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Query",
        to: "/queries",
        icon: <CIcon icon={cilCommentSquare} customClassName="nav-icon" />,
        module: "queries",
      },
      {
        component: CNavItem,
        name: "Query Products",
        to: "/query-products",
        icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
        module: "queries",
        excludeRolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "Follow-up",
        to: "/follow-up",
        icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
        module: "follow_up",
      },
      {
        component: CNavItem,
        name: "Report",
        to: "/query-master/report",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: "queries",
      },
      {
        component: CNavItem,
        name: "Product Lead",
        to: "/product-lead",
        icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
        module: "products",
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Quotation Master",
    to: "/quotations",
    icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Quotation",
        to: "/quotations",
        icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
        module: "quotations",
      },
      {
        component: CNavItem,
        name: "Quotation Products",
        to: "/quotation-products",
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
        module: "quotations",
      },
      {
        component: CNavItem,
        name: "Follow-up",
        to: "/quotation-followup",
        icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
        module: "quotations",
        rolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "Lost Quotation",
        to: "/lost-quotations",
        icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
        module: "quotations",
      },
      {
        component: CNavItem,
        name: "Report",
        to: "/quotation-master/report",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: "quotations",
      },
      {
        component: CNavItem,
        name: "Follow-up Dashboard",
        to: "/followup-dashboard",
        icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
        roles: ["head_of_department", "hod"],
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Business Partner",
    to: "/industries",
    icon: <CIcon icon={cilIndustry} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Customer",
        to: "/industries",
        icon: <CIcon icon={cilIndustry} customClassName="nav-icon" />,
        module: "industries",
      },
      {
        component: CNavItem,
        name: "Customer Contacts",
        to: "/industry-branches",
        icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
        module: "industry_branches",
      },
      {
        component: CNavItem,
        name: "Suppliers",
        to: "/suppliers",
        icon: <CIcon icon={cilFactory} customClassName="nav-icon" />,
        module: "suppliers",
      },
      {
        component: CNavItem,
        name: "Suppliers Contacts",
        to: "/supplier-contacts",
        icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
        module: "suppliers",
      },
    ],
  },
  {
    component: CNavItem,
    name: "Rate Card",
    to: "/rate-cards",
    icon: <CIcon icon={cilList} customClassName="nav-icon" />,
    module: "rate_cards",
  },
  {
    component: CNavItem,
    name: "Task Dashboard",
    to: "/task-dashboard",
    icon: <CIcon icon={cilTask} customClassName="nav-icon" />,
    module: "task_management",
  },
  {
    component: CNavItem,
    name: "Task Bucket",
    to: "/task-bucket",
    icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
    module: "task_bucket",
  },
  {
    component: CNavItem,
    name: "Pro Bucket",
    to: "/pro-bucket",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: "pro_bucket",
  },
  {
    component: CNavItem,
    name: "Local Pro",
    to: "/local-pro",
    icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
    roles: ["procurement"],
  },
  {
    component: CNavItem,
    name: "My Pro Bucket",
    to: "/local-pro",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    roles: ["localprocurement"],
  },
  {
    component: CNavItem,
    name: "Local Purchase",
    to: "/local-purchase",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    roles: ["procurement"],
  },
  {
    component: CNavItem,
    name: "My Purchase",
    to: "/my-purchase",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    roles: ["localpurchase"],
  },
  {
    component: CNavItem,
    name: "Local Purchase",
    to: "/local-purchase",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: "purchase_bucket",
    roles: ["purchase_exicutive"],
  },
  {
    component: CNavItem,
    name: "Purchase Bucket",
    to: "/purchase-bucket",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: "purchase_bucket",
  },
  {
    component: CNavItem,
    name: "Inventory bucket",
    to: "/inventory-bucket",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: "inventory_bucket",
    excludeRolePrefix: "sales",
  },
  {
    component: CNavItem,
    name: "Dispatchment",
    to: "/dispatchment",
    icon: <CIcon icon={cilTruck} customClassName="nav-icon" />,
    module: "dispatchment",
    excludeRolePrefix: "sales",
  },
  {
    component: CNavItem,
    name: "Target Analytics",
    to: "/target-analytics",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: "target_analytics",
  },
  {
    component: CNavItem,
    name: "My Targets",
    to: "/my-targets",
    icon: <CIcon icon={cilTask} customClassName="nav-icon" />,
    rolePrefix: "sales",
  },
  {
    component: CNavGroup,
    name: "Sales Order Master",
    to: "/purchase-order-sidebar",
    icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Sales Orders",
        to: "/purchase-order-sidebar",
        icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
        module: "po_payment",
      },
      {
        component: CNavItem,
        name: "Sales Order Product",
        to: "/po-products",
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
        roles: ["super_admin", "admin", "head_of_department", "hod"],
      },
      {
        component: CNavGroup,
        name: "Order Tracking",
        to: "/order-tracking/purchase",
        items: [
          {
            component: CNavItem,
            name: "Purchase",
            to: "/order-tracking/purchase",
            icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
            roles: ["head_of_department", "hod"],
          },
          {
            component: CNavItem,
            name: "Finance",
            to: "/order-tracking/finance",
            icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
            module: "po_payment",
            excludeRolePrefix: "sales",
          },
          {
            component: CNavItem,
            name: "Inventory",
            to: "/order-tracking/inventory",
            icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
            module: "inventory_bucket",
            excludeRolePrefix: "sales",
          },
          {
            component: CNavItem,
            name: "Dispatch",
            to: "/order-tracking/dispatch",
            icon: <CIcon icon={cilTruck} customClassName="nav-icon" />,
            module: "dispatchment",
            excludeRolePrefix: "sales",
          },
        ],
      },
      {
        component: CNavItem,
        name: "Sales Order History",
        to: "/sales-order-history",
        icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
        module: "po_bucket",
      },
      {
        component: CNavItem,
        name: "Report",
        to: "/sales-order-master/report",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: "po_bucket",
      },
      {
        component: CNavItem,
        name: "Sales Order Bucket",
        to: "/po-bucket",
        icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
        module: "po_bucket",
      },
      {
        component: CNavItem,
        name: "Sales Order payment",
        to: "/po-payment",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "po_payment",
        excludeRolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "Purchase Request",
        to: "/purchase-requests",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        roles: ["head_of_department", "hod"],
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Payment Management",
    to: "/po-payment",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Customer Payments",
        to: "/payment/customer",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "po_payment",
        excludeRolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "OverDue Customer Payments",
        to: "/payment/overdue-customer",
        icon: <CIcon icon={cilClock} customClassName="nav-icon" />,
        roles: ["head_of_department", "hod"],
      },
      {
        component: CNavItem,
        name: "Supplier Payments",
        to: "/payment/supplier",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "billing_request",
        excludeRolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "OverDue Supplier Payments",
        to: "/payment/overdue-supplier",
        icon: <CIcon icon={cilClock} customClassName="nav-icon" />,
        module: "po_payment_backlog",
      },
      {
        component: CNavItem,
        name: "Payment Follow-up",
        to: "/payment/follow-up",
        icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
        roles: ["head_of_department", "hod"],
      },
      {
        component: CNavItem,
        name: "Payment History",
        to: "/payment/history",
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
        rolePrefix: "purchase",
      },
      {
        component: CNavItem,
        name: "Payment Hold",
        to: "/payment/hold",
        icon: <CIcon icon={cilClock} customClassName="nav-icon" />,
        rolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "Sales Order payment",
        to: "/po-payment",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "po_payment",
        excludeRolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "Payment Backlog",
        to: "/hod-payment-backlog",
        icon: <CIcon icon={cilClock} customClassName="nav-icon" />,
        roles: ["head_of_department", "hod"],
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Purchase Master",
    to: "/suppliers",
    icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Suppliers",
        to: "/suppliers",
        icon: <CIcon icon={cilFactory} customClassName="nav-icon" />,
        module: "suppliers",
      },
      {
        component: CNavGroup,
        name: "Purchase",
        to: "/purchase-requests",
        items: [
          {
            component: CNavItem,
            name: "Purchase Requests",
            to: "/purchase-requests",
            icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
            roles: ["head_of_department", "hod"],
          },
          {
            component: CNavItem,
            name: "Local Purchase",
            to: "/local-purchase",
            icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
            module: "purchase_bucket",
          },
          {
            component: CNavItem,
            name: "Brand Purchase",
            to: "/purchase/brand",
            icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
            module: "purchase_bucket",
          },
        ],
      },
      {
        component: CNavItem,
        name: "Purchase Orders",
        to: "/purchase-order-sidebar",
        icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
        module: "po_payment",
      },
      {
        component: CNavItem,
        name: "GRN",
        to: "/purchase/grn",
        icon: <CIcon icon={cilCheckCircle} customClassName="nav-icon" />,
        module: "inventory_bucket",
        excludeRolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "Purchase Return",
        to: "/purchase/return",
        icon: <CIcon icon={cilCart} customClassName="nav-icon" />,
        module: "purchase_bucket",
      },
      {
        component: CNavItem,
        name: "Vendor Payments",
        to: "/purchase/vendor-payments",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "billing_request",
        excludeRolePrefix: "sales",
      },
      {
        component: CNavItem,
        name: "Purchase History",
        to: "/purchase/history",
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
        module: "purchase_bucket",
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Procurement Master",
    to: "/suppliers",
    icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Suppliers",
        to: "/suppliers",
        icon: <CIcon icon={cilFactory} customClassName="nav-icon" />,
        module: "suppliers",
      },
      {
        component: CNavGroup,
        name: "Procurement",
        to: "/purchase-tasks",
        items: [
          {
            component: CNavItem,
            name: "Procurement Requests",
            to: "/purchase-tasks",
            icon: <CIcon icon={cilClipboard} customClassName="nav-icon" />,
            module: "purchase_tasks",
          },
          {
            component: CNavItem,
            name: "Local Procurement",
            to: "/local-pro",
            icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
            roles: ["procurement"],
          },
          {
            component: CNavItem,
            name: "Brand Procurement",
            to: "/procurement/brand",
            icon: <CIcon icon={cilBasket} customClassName="nav-icon" />,
            module: "pro_bucket",
          },
        ],
      },
      {
        component: CNavItem,
        name: "Procurement History",
        to: "/procurement/history",
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
        module: "pro_bucket",
      },
    ],
  },
  {
    component: CNavGroup,
    name: "HR Management",
    to: "/employees",
    icon: <CIcon icon={cilUser} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavGroup,
        name: "Employees",
        to: "/employees",
        items: [
          {
            component: CNavItem,
            name: "Employees",
            to: "/employees",
            icon: <CIcon icon={cilUser} customClassName="nav-icon" />,
            module: "employees",
          },
          {
            component: CNavItem,
            name: "Attendance",
            to: "/hr/attendance",
            icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
            module: "employees",
          },
          {
            component: CNavItem,
            name: "Leave Management",
            to: "/hr/leave",
            icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
            module: "employees",
          },
          {
            component: CNavItem,
            name: "Fuel Management",
            to: "/hr/fuel",
            icon: <CIcon icon={cilTruck} customClassName="nav-icon" />,
            module: "employees",
          },
          {
            component: CNavItem,
            name: "Employees Document",
            to: "/company-documents",
            icon: <CIcon icon={cilFolder} customClassName="nav-icon" />,
            module: null,
            roles: ["head_of_department", "hod"],
          },
        ],
      },
      {
        component: CNavItem,
        name: "Salary Management",
        to: "/hr/salary",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "employees",
      },
      {
        component: CNavItem,
        name: "HR Reports",
        to: "/hr/reports",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: "branch_analytics",
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Report",
    to: "/target-analytics",
    icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Sales Report",
        to: "/reports/sales",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: "target_analytics",
      },
      {
        component: CNavItem,
        name: "Quotation Report",
        to: "/reports/quotation",
        icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
        module: "quotations",
      },
      {
        component: CNavItem,
        name: "Supplier Report",
        to: "/reports/supplier",
        icon: <CIcon icon={cilFactory} customClassName="nav-icon" />,
        module: "suppliers",
      },
    ],
  },
  {
    component: CNavItem,
    name: "Pending Payments",
    to: "/po-payment-backlog",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    module: "po_payment_backlog",
  },
  {
    component: CNavItem,
    name: "Pending payment",
    to: "/pending-payment",
    icon: <CIcon icon={cilClock} customClassName="nav-icon" />,
    /** Sales roles only; no po_payment permission required (read-only assigned POs). */
    rolePrefix: "sales",
  },
  {
    component: CNavItem,
    name: "Billing request",
    to: "/billing-requests",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    module: "billing_request",
    excludeRolePrefix: "sales",
  },
  {
    component: CNavItem,
    name: "Batch Billing Requests",
    to: "/batch-billing-requests",
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    rolePrefix: "purchase",
  },
  {
    component: CNavItem,
    name: "My Visits",
    to: "/my-visits",
    icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
    module: "my_visits",
  },
  {
    component: CNavGroup,
    name: "Branch Settings",
    to: "/zones",
    icon: <CIcon icon={cilMap} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Zones",
        to: "/zones",
        icon: <CIcon icon={cilMap} customClassName="nav-icon" />,
        module: "zones",
      },
      {
        component: CNavItem,
        name: "SubZone",
        to: "/sub-zones",
        icon: <CIcon icon={cilLayers} customClassName="nav-icon" />,
        module: "sub_zones",
      },
      {
        component: CNavItem,
        name: "Employees",
        to: "/employees",
        icon: <CIcon icon={cilUser} customClassName="nav-icon" />,
        module: "employees",
      },
      {
        component: CNavItem,
        name: "Company documents",
        to: "/company-documents",
        icon: <CIcon icon={cilFolder} customClassName="nav-icon" />,
        module: null,
        roles: ["head_of_department", "hod"],
      },
      {
        component: CNavItem,
        name: "Branch Analytics",
        to: "/branch-analytics",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        module: "branch_analytics",
      },
      {
        component: CNavItem,
        name: "Target Dashboard",
        to: "/target-dashboard",
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
        roles: ["head_of_department", "hod"],
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Company Information",
    to: "/sidebar-docs",
    icon: <CIcon icon={cilBuilding} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Companies",
        to: "/companies",
        icon: <CIcon icon={cilBuilding} customClassName="nav-icon" />,
        module: "companies",
      },
      {
        component: CNavItem,
        name: "Branches",
        to: "/branches",
        icon: <CIcon icon={cilLocationPin} customClassName="nav-icon" />,
        module: "branches",
      },
      {
        component: CNavItem,
        name: "Docs",
        to: "/sidebar-docs",
        icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
        module: null,
      },
    ],
  },
  {
    component: CNavGroup,
    name: "Misslanous",
    to: "/rate-master",
    icon: <CIcon icon={cilOptions} customClassName="nav-icon" />,
    module: null,
    items: [
      {
        component: CNavItem,
        name: "Rate Master",
        to: "/rate-master",
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
        module: "rate_cards",
      },
      {
        component: CNavItem,
        name: "Delivery Approval",
        to: "/delivery-approval",
        icon: <CIcon icon={cilCheckCircle} customClassName="nav-icon" />,
        roles: ["super_admin", "admin", "head_of_department", "hod"],
      },
      {
        component: CNavItem,
        name: "Visit Management",
        to: "/visit-management-sidebar",
        icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
        module: "visit_management",
      },
    ],
  },
];

export default _nav;
